create table if not exists public.rti_applications (
  id bigint generated by default as identity primary key,
  user_key text,
  user_name text not null,
  user_address text not null,
  subject text not null,
  department text not null,
  pio_name text,
  pio_address text,
  state text,
  draft text not null,
  filed_date date not null,
  deadline_date date not null,
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

alter table public.rti_applications
  add column if not exists user_key text;

create index if not exists rti_applications_user_name_idx
  on public.rti_applications (user_name);

create index if not exists rti_applications_user_key_idx
  on public.rti_applications (user_key);

create index if not exists rti_applications_filed_date_idx
  on public.rti_applications (filed_date desc);

alter table public.rti_applications enable row level security;

-- For this student demo, the FastAPI backend uses the service role key,
-- so RLS is bypassed by the backend. Do not expose the service role key
-- in the React frontend.
